# Generated by Django 2.2.13 on 2020-11-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20201102_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='mentor_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
