# Generated by Django 2.2.13 on 2021-09-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_appointment_mentor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='video_streaming_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
