district_list=(
	("BAG","Bagerhat"),
	("BAN","Bandarban"),
	("BAR","Barishal"),
	("BHO","Bhola"),
	("BOG","Bogura"),
	("BOR","Barguna"),
	("BRA","Brahmanbaria"),
	("CHA","Chapainawabganj"),
	("CHAN","Chandpur"),
	("CHAT","Chattogram"),
	("CHU","Chuadanga"),
	("COX","Cox's Bazar"),
	("CUM","Cumilla"),
	("DHA","Dhaka"),
	("DIN","Dinajpur"),
	("FAR","Faridpur"),
	("FEN","Feni"),
	("GAI","Gaibandha"),
	("GAZ","Gazipur"),
	("GOP","Gopalganj"),
	("HAB","Habiganj"),
	("JAM","Jamalpur"),
	("JAS","Jashore"),
	("JHA","Jhalokati"),
	("JHE","Jhenaidah"),
	("JOY","Joypurhat"),
	("KHA","Khagrachhari"),
	("KHU","Khulna"),
	("KIS","Kishoreganj"),
	("KUR","Kurigram"),
	("KUS","Kushtia"),
	("LAK","Lakshmipur"),
	("LAL","Lalmonirhat"),
	("MAD","Madaripur"),
	("MAG","Magura"),
	("MAN","Manikganj"),
	("MEH","Meherpur"),
	("MOU","Moulvibazar"),
	("MUN","Munshiganj"),
	("MYM","Mymensingh"),
	("NAO","Naogaon"),
	("NAR","Narail"),
	("NARAY","Narayanganj"),
	("NARS","Narsingdi"),
	("NAT","Natore"),
	("NET","Netrokona"),
	("NIL","Nilphamari"),
	("NOA","Noakhali"),
	("PAB","Pabna"),
	("PAN","Panchagarh"),
	("PAT","Patuakhali"),
	("PIR","Pirojpur"),
	("RAJ","Rajbari"),
	("RAJS","Rajshahi"),
	("RAN","Rangamati"),
	("RANG","Rangpur"),
	("SAT","Satkhira"),
	("SHA","Shariatpur"),
	("SHE","Sherpur"),
	("SIR","Sirajganj"),
	("SUN","Sunamganj"),
	("SYL","Sylhet"),
	("TAN","Tangail"),
	("THA","Thakurgaon"),
)

divisions_list=(
	("BAR","Barisal"),
	("CHI","Chittagong"),
	("DHA","Dhaka"),
	("KHU","Khulna"),
	("MYM","Mymensingh"),
	("RAJ","Rajshahi"),
	("RAN","Rangpur"),
	("SYL","Sylhet"),
)

category=(
	("BUS","Business"),
	("CAR","Career"),
	("HNF","Health & Fitness"),
	("LFS","Life Style"),
	("PRD","Personal Development"),
	("TNE","Teaching & Education"),
)

sex=(
	("Male","Male"),
	("Female","Female"),
	("Other","Other"),
)

price_choices = (
    ("500","৳500"),
    ("1000","৳1000"),
    ("1500","৳1500"),
    ("2000","৳2000"),
)
