# Generated by Django 2.2.13 on 2020-10-27 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='mentor_username',
            new_name='mentor_Name',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='name',
        ),
    ]
