# Generated by Django 2.2.13 on 2020-10-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_auto_20201027_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='cover_photo_1',
            field=models.ImageField(blank=True, upload_to='photos/mentors/cover/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentors_picture',
            field=models.ImageField(blank=True, upload_to='photos/dp/mentors/%Y/%m/%d/'),
        ),
    ]
