# Generated by Django 2.2.13 on 2020-10-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_auto_20201027_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
