# Generated by Django 2.2.13 on 2020-10-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0005_auto_20201029_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='district',
            field=models.CharField(blank=True, choices=[('BAG', 'Bagerhat'), ('BAN', 'Bandarban'), ('BAR', 'Barishal'), ('BHO', 'Bhola'), ('BOG', 'Bogura'), ('BOR', 'Barguna'), ('BRA', 'Brahmanbaria'), ('CHA', 'Chapainawabganj'), ('CHAN', 'Chandpur'), ('CHAT', 'Chattogram'), ('CHU', 'Chuadanga'), ('COX', "Cox's Bazar"), ('CUM', 'Cumilla'), ('DHA', 'Dhaka'), ('DIN', 'Dinajpur'), ('FAR', 'Faridpur'), ('FEN', 'Feni'), ('GAI', 'Gaibandha'), ('GAZ', 'Gazipur'), ('GOP', 'Gopalganj'), ('HAB', 'Habiganj'), ('JAM', 'Jamalpur'), ('JAS', 'Jashore'), ('JHA', 'Jhalokati'), ('JHE', 'Jhenaidah'), ('JOY', 'Joypurhat'), ('KHA', 'Khagrachhari'), ('KHU', 'Khulna'), ('KIS', 'Kishoreganj'), ('KUR', 'Kurigram'), ('KUS', 'Kushtia'), ('LAK', 'Lakshmipur'), ('LAL', 'Lalmonirhat'), ('MAD', 'Madaripur'), ('MAG', 'Magura'), ('MAN', 'Manikganj'), ('MEH', 'Meherpur'), ('MOU', 'Moulvibazar'), ('MUN', 'Munshiganj'), ('MYM', 'Mymensingh'), ('NAO', 'Naogaon'), ('NAR', 'Narail'), ('NARAY', 'Narayanganj'), ('NARS', 'Narsingdi'), ('NAT', 'Natore'), ('NET', 'Netrokona'), ('NIL', 'Nilphamari'), ('NOA', 'Noakhali'), ('PAB', 'Pabna'), ('PAN', 'Panchagarh'), ('PAT', 'Patuakhali'), ('PIR', 'Pirojpur'), ('RAJ', 'Rajbari'), ('RAJS', 'Rajshahi'), ('RAN', 'Rangamati'), ('RANG', 'Rangpur'), ('SAT', 'Satkhira'), ('SHA', 'Shariatpur'), ('SHE', 'Sherpur'), ('SIR', 'Sirajganj'), ('SUN', 'Sunamganj'), ('SYL', 'Sylhet'), ('TAN', 'Tangail'), ('THA', 'Thakurgaon')], default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='divisions',
            field=models.CharField(blank=True, choices=[('BAR', 'Barisal'), ('CHI', 'Chittagong'), ('DHA', 'Dhaka'), ('KHU', 'Khulna'), ('MYM', 'Mymensingh'), ('RAJ', 'Rajshahi'), ('RAN', 'Rangpur'), ('SYL', 'Sylhet')], default=None, max_length=300),
        ),
    ]
