# Generated by Django 2.2.13 on 2020-10-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_auto_20201029_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=50),
        ),
    ]
