# Generated by Django 2.2.13 on 2020-11-28 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0008_auto_20201029_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
